language: node_js
node_js:
  - "8.2.1"

install:
  - npm install newman

before_script:
  - npm start &

script:
- node_modules/.bin/newman run https://www.getpostman.com/collections/6bdc3692b12e95b33775